### ISSUE TITLE
マークダウンテスト

### ISSUE THREAD

**Issue by TheGK-rh** [TheGK-rh/appleweb#3]
# GoQMieruca EC-CUBE4系向けプラグイン
以下、開発環境の構築方法から、プラグインのインストール方法などをまとめています。<br>
**開発中の注意点**は必ず確認してください。<br>
3.0.xからの変更点（[公式](https://doc4.ec-cube.net/plugin_spec)）

## 開発環境構築
1. [EC-CUBE 4.0](https://github.com/EC-CUBE/ec-cube)を`git clone`
2. `cd path/to/ec-cube` ec-cubeディレクトリに移動
3. .envを作成`cp .env.dist .env`
4. .envの修正（postgreSQL、メールデバック用サーバー使用）
```
# DATABASE_URL=sqlite:///var/eccube.db
DATABASE_URL=postgresql://postgres/eccubedb?user=dbuser&password=secret
# MAILER_URL=null://localhost
MAILER_URL=smtp://mailcatcher:1025
```
5. docker-compose.ymlのMYSQLを削除もしくはコメントアウト（使用しないので）
```
### MySQL ##################################
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eccubedb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      - backend
```
6. コンテナ起動 `docker-compose up -d`
7. インストールスクリプトを実行（初期化されるので初回以外は実行しないように）
```
docker-compose exec -u www-data ec-cube bin/console eccube:install
```
下記の内容が表示されますが、.envはすでに修正しているので全てEnterでOKです。
```
EC-CUBE Installer Interactive Wizard
====================================
 If you prefer to not use this interactive wizard, define the environment valiables as follows:
  $ export APP_ENV=dev
  $ export APP_DEBUG=1
  $ export DATABASE_URL=database_url
  $ export DATABASE_SERVER_VERSION=server_version
  $ export MAILER_URL=mailer_url
  $ export ECCUBE_AUTH_MAGIC=auth_magic
  ... and more
  $ php bin/console eccube:install --no-interaction
 Database Url [mysql://dbuser:secret@mysql/eccubedb]:
 >
 Mailer Url [smtp://mailcatcher:1025]:
 >
 Auth Magic [xxxxxx]:
 >
```
8. EC-CUBEのサイトがLocalで見れるか確認する。<br>
フロント側 http://localhost:8080/<br>
管理画面 http://localhost:8080/admin
```
デフォルトのID/PW 公式サイトのデモサイトと同じ。
ID: admin
PW: password
```
9. `cd ec-cube/app/Pulgin`に移動
10. このリポジトリを`git clone`、ルートディレクトリ名をGoqmierucaPlugin_v4に変更。（下記コマンドで同時処理できます）
```
git clone https://github.com/GoQSystemInc/mieruca-eccube-plugin-v4.git ./GoqmierucaPlugin_v4
```
- 以降のコンテナの起動と停止
```
docker-compose up -d
docker-compose down
```

## プラグインのインストール・有効化方法
**プラグインインストールの前に認証キーを設定してください。（設定してないとHTTP ERROR 500が発生）**<br>
`管理画面->オーナーズストア->認証キー発行 画面`
- プラグインをインストール
- プラグインを有効化
```
docker-compose exec ec-cube bin/console eccube:plugin:install --code=GoqmierucaPlugin_v4
docker-compose exec ec-cube bin/console eccube:plugin:enable --code=GoqmierucaPlugin_v4
```
[オーナーズストア経由のインストールをテストする場合](https://doc4.ec-cube.net/plugin_mock_package_api)）

## 開発中の注意点
- localhost上（GUI）で開発中のプラグインのアンインストール・削除は行わないこと。
- ターミナル上で、公式にある下記削除コマンドを実行しないこと。
```
bin/console eccube:plugin:uninstall --code=プラグインコード --uninstall-force=true
```
**実行すると、app/Plugin配下のソースがすべてシステム的に削除される(=ゴミ箱内にも存在しない)ため。つまり、.gitディレクトリが復帰できなくなり、ローカルブランチやstashした内容が全て消え、それまでの作業が水の泡に。。。**

## 開発が終わったら、docker開発環境を全て削除しましょう。
- docker-composeで作成したEC-CUBEのコンテナ、イメージ、ボリューム、ネットワークを削除します。

` cd path/to/ec-cube` ec-cubeディレクトリで下記コマンドを実行。
```
docker-compose down --rmi all --volumes --remove-orphans
```
